### ISSUE TITLE
Editor Null exception adding camera rig to scene

### ISSUE THREAD

**Issue by sphaero** [ValveSoftware/steamvr_unity_plugin#57]
Just trying the SteamVR package on the Linux Editor. Imported the package through the asset store. As soon as I add the camera rig to the scene the editor crashes:

System details:
Unity: 5.6.3xf1Linux
OS: Ubuntu Xenial (16.04)
SteamVR runtime is not installed (on purpose)

Tried Unity 2017.3.0b1, and Debian Testing as well, same result.

Editor.log:
```
(Filename: Assets/SteamVR/Scripts/SteamVR_GameView.cs Line: 14)

Receiving unhandled NULL exception
#0  0x007ffd92766c40 in funlockfile
#1  0x007ffd927672e0 in _dl_find_dso_for_object
#2  0x007ffd927672f0 in _dl_rtld_di_serinfo
#3  0x007ffd92767440 in dlerror
#4  0x007ffd92767460 in dlclose
#5  0x007ffd92767470 in VR_InitInternal
#6  0x007ffd927674b0 in (Unknown)
#7  0x007ffd927674c0 in (Unknown)
#8  0x007ffd927674d0 in (Unknown)
#9  0x007ffd927674e0 in (Unknown)
#10 0x007ffd927674f0 in (Unknown)
#11 0x007ffd92767500 in (Unknown)
#12 0x007ffd92767510 in (Unknown)
#13 0x007ffd92767520 in mono_set_defaults
#14 0x007ffd92767900 in mono_runtime_invoke
#15 0x007ffd92767930 in scripting_method_invoke(ScriptingMethodPtr, Scripti
ngObjectPtr, ScriptingArguments&, ScriptingExceptionPtr*, bool)
#16 0x007ffd92767970 in ScriptingInvocation::Invoke(ScriptingExceptionPtr*,
 bool)
#17 0x007ffd927679a0 in MonoBehaviour::CallMethodIfAvailable(int)
#18 0x007ffd92767b30 in void BaseBehaviourManager::CommonUpdate<BehaviourMa
nager>()
#19 0x007ffd92767b90 in BehaviourManager::Update()
#20 0x007ffd92767bb0 in PlayerLoop()
#21 0x007ffd92767bd0 in Application::UpdateScene(bool)
#22 0x007ffd92767c50 in Application::UpdateSceneIfNeeded()
#23 0x007ffd92767c70 in Application::TickTimer()
#24 0x007ffd92767e80 in MainMessageIteration(void*)
#25 0x007ffd92767e90 in g_source_get_time
#26 0x007ffd92767eb0 in g_main_context_dispatch
#27 0x007ffd92767f40 in g_main_context_dispatch
#28 0x007ffd92767fa0 in g_main_loop_run
#29 0x007ffd92767fd0 in gtk_main
#30 0x007ffd92768050 in main
#31 0x007ffd92768960 in __libc_start_main
#32 0x007ffd92768a20 in _start
```

**Comment by johnv-valve** [comment]
We are still working with Unity to get SteamVR on Linux working in Unity and this applies to both the player and editor.
